/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-highest": "#e1e3e4",
          "primary-container": "#1b1b1b",
          "surface-container-low": "#f3f4f5",
          "primary-fixed-dim": "#c6c6c6",
          "secondary": "#585f6c",
          "tertiary-fixed-dim": "#c0c6db",
          "on-tertiary-fixed": "#141b2b",
          "outline": "#7e7576",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#141b2b",
          "on-tertiary-fixed-variant": "#404758",
          "surface-variant": "#e1e3e4",
          "surface-container": "#edeeef",
          "on-secondary": "#ffffff",
          "primary-fixed": "#e2e2e2",
          "tertiary-fixed": "#dce2f7",
          "surface-bright": "#f8f9fa",
          "on-primary-fixed-variant": "#474747",
          "on-primary": "#ffffff",
          "surface-tint": "#5e5e5e",
          "secondary-fixed": "#dce2f3",
          "surface-container-lowest": "#ffffff",
          "surface": "#f8f9fa",
          "on-secondary-container": "#5e6572",
          "on-primary-container": "#848484",
          "on-surface-variant": "#4c4546",
          "on-error": "#ffffff",
          "on-secondary-fixed": "#151c27",
          "surface-container-high": "#e7e8e9",
          "on-primary-fixed": "#1b1b1b",
          "on-error-container": "#93000a",
          "secondary-fixed-dim": "#c0c7d6",
          "primary": "#000000",
          "secondary-container": "#dce2f3",
          "inverse-primary": "#c6c6c6",
          "surface-dim": "#d9dadb",
          "on-tertiary-container": "#7d8497",
          "outline-variant": "#cfc4c5",
          "inverse-on-surface": "#f0f1f2",
          "error-container": "#ffdad6",
          "on-surface": "#191c1d",
          "on-background": "#191c1d",
          "background": "#f8f9fa",
          "inverse-surface": "#2e3132",
          "error": "#ba1a1a",
          "on-secondary-fixed-variant": "#404754",
          "tertiary": "#000000"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "md": "1.5rem",
          "container-max": "1200px",
          "xs": "0.5rem",
          "sm": "1rem",
          "gutter": "24px",
          "xl": "4rem",
          "margin-mobile": "16px",
          "lg": "2rem",
          "unit": "4px"
      },
      "fontFamily": {
          "headline-lg-mobile": ["Geist"],
          "code": ["Geist"],
          "label-sm": ["Geist"],
          "headline-lg": ["Geist"],
          "body-md": ["Inter"],
          "display-xl": ["Geist"],
          "body-lg": ["Inter"],
          "headline-md": ["Geist"],
          "display-xl-mobile": ["Geist"]
      },
      "fontSize": {
          "headline-lg-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "code": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
          "label-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
          "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
          "display-xl": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
          "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
          "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "display-xl-mobile": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
